/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_GSTACK 0

#define HAVE_GTK3 1

#define HAVE_GTK4 0

#define HAVE_LIBEVDEV_DISABLE_PROPERTY 0

#define HAVE_LIBSYSTEMD 0

#define HAVE_LIBWACOM 1

#define HAVE_LOCALE_H 1

#define HAVE_VERSIONSORT 1

#define HTTP_DOC_LINK "https://wayland.freedesktop.org/libinput/doc/1.19.4"

#define LIBINPUT_QUIRKS_DIR "/usr/share/libinput"

#define LIBINPUT_QUIRKS_OVERRIDE_FILE "/etc/libinput/local-overrides.quirks"

#define LIBINPUT_QUIRKS_SRCDIR ""

#define LIBINPUT_TOOL_PATH ""

#define MESON_BUILD_ROOT ""

#define _GNU_SOURCE 1

